jobs:
  deploy:
    runs-on: [self-hosted, linux]  # Using selsf-hosted runner with the linux label

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy the Pod
        run: |
          kubectl apply -f nginx-pod.yaml
